name: Deploy Web App via ARM Template

on:
  push:
    branches:
      - master

env:
  resourceGroupName: 'DevOps_BestPractices_Demo_Dev'
  appServicePlaneName: 'DevopsBestPracticesPlanDev'
  webAppName: 'devops-bestpractices-demo-dev'
  appInsightsName: 'devops-bestpractices-demo-ai-dev'

jobs:
  deploy-arm-template-and-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        id: arm-template-deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            INSTRUMENTATION_KEY=`az deployment group create --resource-group $resourceGroupName --template-file ./ARMDeployment/azuredeploy.json --parameters web_app_name=$webAppName app_service_plan_name=$appServicePlaneName app_insights_name=$appInsightsName --query properties.outputs.AppInsightsInstrumentationKey`

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
        
      # dotnet build, test, and publish
      - name: dotnet build
        run: dotnet build --configuration Release
      - name: dotnet test
        run: dotnet test --configuration Release
      - name: dotnet publish
        run: |
          dotnet publish ./DevOpsBestPractices/DevOpsBestPractices.csproj -c Release -o ${{env.DOTNET_ROOT}}/devopsbestpractices 

      - name: 'Deploy Azure WebApp'
        uses: azure/webapps-deploy@v1
        with: 
          app-name: '${{ env.webAppName }}'
          package: ${{env.DOTNET_ROOT}}/devopsbestpractices
          
      - name: "Set Web App Settings"
        uses: azure/appservice-settings@v1
        with:
          app-name: '${{ env.webAppName }}'
          app-settings-json: >-
            [{"name": "APPINSIGHTS_INSTRUMENTATIONKEY", "value": "${{ env.INSTRUMENTATION_KEY }}", "slotSetting": false}]
        id: settings

