name: Deploy Web App to Production via ARM Template

on:
  push:
    branches:
      - release

env:
  resourceGroupName: 'DevOps_BestPractices_Demo_Prod'
  appServicePlanName: 'DevopsBestPracticesPlanProd'
  webAppName: 'devops-bestpractices-demo-prod'
  appInsightsName: 'devops-bestpractices-demo-ai-prod'

jobs:
  deploy-arm-template-and-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@release

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PROD_AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        id: deploy-arm-template
        uses: whiteducksoftware/azure-arm-action-js@v3
        with:
          resourceGroupName: ${{ env.resourceGroupName }}
          templateLocation: ./ARMDeployment/azuredeploy.json
          parameters: web_app_name=${{ env.webAppName }} app_service_plan_name=${{ env.appServicePlanName }} app_insights_name=${{ env.appInsightsName }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
        
      # dotnet build, test, and publish
      - name: dotnet build
        run: dotnet build --configuration Release
      - name: dotnet test
        run: dotnet test --configuration Release
      - name: dotnet publish
        run: |
          dotnet publish ./DevOpsBestPractices/DevOpsBestPractices.csproj -c Release -o ${{env.DOTNET_ROOT}}/devopsbestpractices 

      - name: 'Deploy Azure WebApp'
        uses: azure/webapps-deploy@v1
        with: 
          app-name: '${{ env.webAppName }}'
          package: ${{env.DOTNET_ROOT}}/devopsbestpractices
          